[package]
name = "protected-database"
version = "0.1.0"
authors = ["cybercrypt <cyber-crypt.com>"]
edition = "2018"

[dependencies]
mysql = "18.2.0"
reqwest = { version = "0.10.6", features = ["blocking"] }
structopt = "0.3.14"
